### PR TITLE
draft: Chore/bootstrap app

### PR DESCRIPTION
**Pull request by simondmansson**
Base setup with a cmd folder with a web and cli app and a pkg folder for libraries used by the applications. 

As an example `pkg/storage/pocketbase` could contain files that can input links, lists to etc pocketbase. The applications import and use the same insertLink function. 

Inspired by https://github.com/golang-standards/project-layout

### CODE REVIEW

**Comment by simondmansson** [comment]
I think I should redo this without pocketbase until we have figured out how to proceed with #2

**Comment by namatoj** [comment]
Looks great!

**Review by namatoj — APPROVED** [review]
Looks good! 👍

**Comment by namatoj** [comment]
> I think I should redo this without pocketbase until we have figured out how to proceed with #2

Oh crap! I saw this too late.

But I think we can still go with this.

**Pull request merged**
